# -*- coding: utf-8 -*-
"""convert_tool.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k7ruhvYRkXN9T1310hzeHNGnuRIhWC8W
"""

import csv  # CSVファイルの読み書き
import json # JSON形式データの読み書き
import sys  # ファイルパスを受け取る
import os   # ファイルの絶対パス表示と存在確認に使用

# ファイル変換
def main():

  print("--- START DEBUG ---")
  if len(sys.argv) < 2:
    print("ERROR [Main]: コマンドライン引数が見つかりません。")
    print(f"DEBUG [Main]: プログラム開始。入力ファイル: {sys.argv[1]}")
    sys.exit(1)

  input_file = sys.argv[1] # 指定したファイル名

  if not os.path.exists(input_file):
    print(f"ERROR [Main]: 指定されたファイル '{input_file}' が見つかりません。パスを確認してください。")
    sys.exit(1)

  if input_file.endswith('.csv'):
    csv_to_json(input_file)
  elif input_file.endswith('.json'):
    json_to_csv(input_file)
  else:
    print(f"エラー: サポートされていないファイル形式 '{input_file}' です。(.csv または .json のみ)")
    print("--- END DEBUG ---")
    sys.exit(1)

# CSVファイルを読み込み、JSONファイルとして出力
def csv_to_json(csv_file_path):

  data = []

  try:
    with open(csv_file_path, mode='r', encoding='utf-8', errors='ignore') as file: # CSVファイルの読み込み
      csv_reader = csv.DictReader(file)

      row_count = 0
      for row in csv_reader: # リストに格納
        data.append(row)
        row_count += 1

  except Exception as e:
    print(f"FATAL ERROR [CSV to JSON - READ]: CSVファイルの読み込み中に予期せぬエラーが発生しました: {e}")
    return

  if not data:
    print("WARNING [CSV to JSON]: 読み込まれたデータが空でした。CSVにヘッダー行以外のデータがあるか確認してください。")
    return

  json_file_path = csv_file_path.replace('.csv', '.json') # ファイル名変更

  try:
    with open(json_file_path, mode='w', encoding='utf-8') as file: # JSONファイルへの書き出し
      json.dump(data, file, ensure_ascii=False, indent=4) # JSON出力
    print(f"✅ 変換が完了しました: {csv_file_path} -> {json_file_path}")
    print(f" データ件数: {len(data)}件")
  except Exception as e:
    print(f"FATAL ERROR [CSV to JSON - WRITE]: JSONファイルの書き出し中にエラーが発生しました: {e}")

# JSONファイルを読み込み、CSVファイルとして出力
def json_to_csv(json_file_path):

  data = []

  try:
    with open(json_file_path, mode='r', encoding='utf-8') as file: #JSONファイルの読み込み
      data = json.load(file)
  except FileNotFoundError:
    print(f"エラー: ファイル '{json_file_path}' が見つかりません。")
    return
  except json.JSONDecodeError: # JSON形式が壊れている
    print(f"エラー: ファイル '{json_file_path}' は無効なJSON形式です。")
    return
  except Exception as e:
    print(f"JSONファイルの読み込み中にエラーが発生しました: {e}")
    return

  if not data or not isinstance(data, list) or not all(isinstance(i, dict) for i in data):
    print("エラー: JSONファイルには、有効な辞書のリストが含まれている必要があります。")
    return

  fieldnames = list(data[0].keys())
  csv_file_path = json_file_path.replace('.json', '.csv') # ファイル名変更

  try:
    with open(csv_file_path, mode='w', encoding='utf-8', newline='') as file:
      writer = csv.DictWriter(file, fieldnames=fieldnames)
      writer.writeheader() # ヘッダー行を出力
      writer.writerows(data) # 一括でデータ行として書き込み
      print(f"✅ 変換が完了しました: {json_file_path} -> {csv_file_path}")
      print(f" データ件数: {len(data)}件")
  except Exception as e:
      print(f"CSVファイルの書き出し中にエラーが発生しました: {e}")

if __name__ == "__main__":
    main()

